### ISSUE TITLE
Upgraded to Lightinject 0.99.74 and LI 4.1.1 and get error on startup

### ISSUE THREAD

**Issue by KennethJakobsen** [rebus-org/Rebus.LightInject#1]
When I Upgraded i got the following error: 
Method not found: 'Void  LightInject.IServiceRegistry.Register(System.Func`2<LightInject.IServiceFactory,!!0>)'.

On this line:
 var bus = Configure.With(new LightInjectContainerAdapter(new LightInject.ServiceContainer()))

Regards Kenneth

**Comment by mookid8000** [comment]
Hmm, that's weird – [Rebus.LightInject 0.99.74](https://www.nuget.org/packages/Rebus.LightInject/0.99.74) is compiled with LightInject 4.0.9, so it must work with that version.

Could you try and downgrade to 4.0.9 and see if that fixes it?

**Comment by KennethJakobsen** [comment]
Downgrading seems to fix the problem!

**Comment by mookid8000** [comment]
Good 😄 

When Rebus 2.0.0 comes out before the end of this month, the LightInject adapter will be compiled against the latest LightInject.
